---
- hosts: docker_host
  become: true
  vars:
    - amnotbot_config_path: /home/gpoppino/amnotbot
    - amnotbot_image: gpoppino/amnotbot:latest

  tasks:
    - include_tasks: tasks/docker.yml

    - name: Load Amnotbot's Docker Image
      docker_container:
        name: amnotbot
        image: "{{ amnotbot_image }}"
        pull: true
        state: started
        volumes:
            - "{{ amnotbot_config_path }}:/home/amnotbot/.amnotbot"

